server:
  port: ${PORT:9000}
---
spring:
  application:
    name: api-challenge
---
management:
  endpoint:
    health:
      show-components: ALWAYS
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - actuator
          - health
          - info
          - metrics
          - prometheus
          - openapi
          - swagger-ui
        exclude:
---
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
---
spring:
  jpa:
    generate-ddl: true
    show-sql: true
  r2dbc:
    url: r2dbc:postgres://${DB_HOST:localhost:7432}/championship?useSSL=false&serverTimezone=America/Lima
    username: ${DB_USER:wala}
    password: ${DB_PASSWORD:12345}
    pool:
      initial-size: 1
      max-idle-time: 30s
      max-size: 5
      validation-query: "SELECT 1"
      max-create-connection-time: 30s
  data:
    r2dbc:
      repositories:
        enabled: true
